navikt/k9-format

.github/workflows/pull-requests.yml, pom.xml
La også til workflow for Pull requests
=> Forrige PR innhold breaking endringer

.gitignore, pom.xml, soknad-omsorgspenger-utbetaling/pom.xml, soknad-omsorgspenger-utbetaling/soknad-omsorgspenger-utbetaling.iml, soknad-omsorgspenger-utbetaling/src/main/java/no/nav/k9/søknad/omsorgspenger/utbetaling/OmsorgspengerUtbetalingSøknad.java, soknad-omsorgspenger-utbetaling/src/main/java/no/nav/k9/søknad/omsorgspenger/utbetaling/OmsorgspengerUtbetalingSøknadValidator.java, soknad-omsorgspenger-utbetaling/src/test/java/no/nav/k9/søknad/omsorgspenger/utbetaling/OmsorgspengerUtbetalingSøknadTest.java, soknad-omsorgspenger-utbetaling/src/test/java/no/nav/k9/søknad/omsorgspenger/utbetaling/OmsorgspengerUtbetalingSøknadValidatorTest.java, soknad-omsorgspenger-utbetaling/src/test/java/no/nav/k9/søknad/omsorgspenger/utbetaling/TestUtils.java, soknad-omsorgspenger-utbetaling/src/test/resources/komplett-søknad.json
- Lik som for Omsorgspenger (rammevedtak) - men ikke noe referanse til barn
=> Søknad for Omsorgspenger utbetaling 

soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/PleiepengerSyktBarnValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/UttakPeriodeInfo.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/arbeidstid/ArbeidstidInfo.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/arbeidstid/ArbeidstidPeriodeInfo.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/tilsyn/TilsynPeriodeInfo.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/tilsyn/Tilsynsordning.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/psb/PleiepengerBarnSøknadValidatorTest.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/psb/TestUtils.java, soknad/src/test/resources/ytelse/psb/komplett-søknad.json
Endrer på formatet for timerPerDag for PSB og flyttet Faktisk opp et nivå
=> Endrer på BigDeismal til duration for timerPerDag. 

ettersendelse/src/main/java/no/nav/k9/ettersendelse/Ettersendelse.java, ettersendelse/src/main/java/no/nav/k9/ettersendelse/EttersendelseValidator.java, soknad-omsorgspenger-utbetaling/src/main/java/no/nav/k9/søknad/omsorgspenger/utbetaling/arbeidstaker/OmsorgspengerUtbetalingSøknad.java, soknad-omsorgspenger-utbetaling/src/main/java/no/nav/k9/søknad/omsorgspenger/utbetaling/snf/OmsorgspengerUtbetalingSøknad.java, soknad-omsorgspenger/src/main/java/no/nav/k9/søknad/omsorgspenger/OmsorgspengerSøknadValidator.java, soknad/src/main/java/no/nav/k9/søknad/felles/Feil.java, soknad/src/main/java/no/nav/k9/søknad/felles/Versjon.java, soknad/src/main/java/no/nav/k9/søknad/felles/aktivitet/Arbeidstaker.java, soknad/src/main/java/no/nav/k9/søknad/felles/aktivitet/Frilanser.java, soknad/src/main/java/no/nav/k9/søknad/felles/aktivitet/Organisasjonsnummer.java, soknad/src/main/java/no/nav/k9/søknad/felles/aktivitet/SelvstendigNæringsdrivende.java, soknad/src/main/java/no/nav/k9/søknad/felles/personopplysninger/Barn.java, soknad/src/main/java/no/nav/k9/søknad/felles/personopplysninger/Bosteder.java, soknad/src/main/java/no/nav/k9/søknad/felles/personopplysninger/Utenlandsopphold.java, soknad/src/main/java/no/nav/k9/søknad/felles/type/Landkode.java, soknad/src/main/java/no/nav/k9/søknad/felles/type/NorskIdentitetsnummer.java, soknad/src/main/java/no/nav/k9/søknad/felles/type/Språk.java, soknad/src/main/java/no/nav/k9/søknad/felles/type/SøknadId.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/utvidetrett/v1/OmsorgspengerMidlertidigAlene.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/OmsorgspengerUtbetaling.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/OmsorgspengerUtbetalingValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/PleiepengerSyktBarn.java, soknad/src/test/java/no/nav/søknad/ytelse/omsorgspenger/utvidetrett/OmsorgspengerMidlertidigAleneValidatorTest.java
lagt til begrunnelse på midlertidig alene
=> fix: fjerner public fields som går i beina på annotation mapping.

soknad-omsorgspenger-utbetaling/src/test/java/no/nav/k9/søknad/omsorgspenger/utbetaling/snf/TestUtils.java, soknad-omsorgspenger-utbetaling/src/test/resources/snf/komplett-søknad.json, soknad/src/main/java/no/nav/k9/søknad/felles/aktivitet/Frilanser.java, soknad/src/main/java/no/nav/k9/søknad/felles/fravær/FraværPeriode.java, soknad/src/main/java/no/nav/k9/søknad/felles/fravær/FraværÅrsak.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/YtelseValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/OmsorgspengerUtbetalingValidator.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/OmsorgspengerUtbetalingValidatorTest.java, soknad/src/test/resources/ytelse/omp/utbetaling/komplett-søknad-omp-utbetaling-snf.json, soknad/src/test/resources/ytelse/omp/utbetaling/minimum-søknad-omp-utbetaling-snf.json
Samt, validerer på frilanser felter.
=> Utvider fraværperiode med fraværårsak og legger på sluttdato på frilanser.

soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/OmsorgspengerUtbetalingValidator.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/OmsorgspengerUtbetalingValidatorTest.java
Sluttdato på frilanser er ikke prodsatt i dialogen.
=> Deaktiverer validering på frilanser.

soknad/src/main/java/no/nav/k9/søknad/ytelse/pls/v1/Pleietrengende.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/pls/SøknadJsonEksempel.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/pls/v1/SøknadJsonTest.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/pls/v1/YtelseEksempel.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/pls/v1/YtelseTest.java, soknad/src/test/resources/ytelse/pls/søknad-med-pleietrengende-norskident-og-fødselsdato.json, soknad/src/test/resources/ytelse/pls/søknad-uten-pleietrengende-info.json, soknad/src/test/resources/ytelse/pls/søknad-uten-pleietrengende-norskident.json
Enten norskIdentitetsnummer eller fødselsdato må være satt.
Markerer konstruktør med parametere som utgått. 
Verdier settes via setter-metoder. Nullability sjekkes i hver metode.
=> Gjør norskIdentitetsnummer nullable og legger på validering.

soknad/src/main/java/no/nav/k9/søknad/Validator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/Ytelse.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/YtelseValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/olp/v1/OpplæringspengerSøknadValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/olp/v1/OpplæringspengerYtelseValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/utvidetrett/v1/OmsorgspengerAleneOmsorg.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/utvidetrett/v1/OmsorgspengerAleneOmsorgSøknadValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/utvidetrett/v1/OmsorgspengerKroniskSyktBarn.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/utvidetrett/v1/OmsorgspengerKroniskSyktBarnSøknadValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/utvidetrett/v1/OmsorgspengerMidlertidigAlene.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/utvidetrett/v1/OmsorgspengerMidlertidigAleneSøknadValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/utvidetrett/v1/RammevedtakSøknadValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/OmsorgspengerUtbetalingSøknadValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/OmsorgspengerUtbetalingValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/pls/v1/PleiepengerLivetsSluttfaseSøknadValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/pls/v1/PleiepengerLivetsSluttfaseYtelseValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/PleiepengerSyktBarnSøknadValidator.java
* tilbyr alternativer (søknadvalidatorer også for ramme-søknader)
* fjerner duplisert kode (arv)
* fikser sammenligning ved compareTo
=> Deprekere YtelseValidator-er, småforbedringer

soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/OmsorgspengerUtbetalingSøknadValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/OmsorgspengerUtbetalingValidator.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/OmsorgspengerUtbetalingValidatorTest.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/OmsorgspengerUtbetalingValidatorV1_0_0Test.java
Med gyldige søknadsperioder menes det eksisterende søknadsperioder som eksisterer i k9-sak.
=> Validerer mot gyldige søknadsperioder for omsorgspengerutbetaling.

soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/OmsorgspengerUbetalingDelvalidatorEndringsperioder.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/OmsorgspengerUtbetalingValidator.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/ValideringsAvbrytendeFeilException.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/omsorgspenger/v1/OmsorgspengerUtbetalingValidatorTest.java
Validering av like perioder på samme aktivitetsfravær eller samme arbeidsgiver feiler.
Validering av like perioder på ulike aktivitetsfravær eller ulike arbeidsgiver feiler ikke.
=> Validere gyldigeperioder per aktivitetstype og pr. arbeidsgiver

soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/DataBruktTilUtledning.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/psb/YtelseEksempel.java, soknad/src/test/resources/ytelse/psb/komplett-søknad.json
Man skal kunne spore tilbake til hvilket spørsmål og informasjon søker har sett ved innsending av søknad.
=> Legger til git-sha for sporing i ettertid.

soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/UkjentArbeidsforhold.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/arbeidstid/Arbeidstaker.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/psb/YtelseEksempel.java, soknad/src/test/resources/ytelse/psb/komplett-søknad.json
Det er ment å brukes i visninger som e.g. i PDF.
=> Legger til støtte for organisasjonsnavn i Arbeidstaker og UkjentArbeidsforhold

soknad/src/main/java/no/nav/k9/søknad/felles/Versjon.java, soknad/src/test/java/no/nav/k9/søknad/felles/VersjonTest.java
Planlegger å bruke dette til å toggle av og på ny funksjonalitet basert på versjon.
=> Comparable Versjon

konstant/pom.xml, konstant/src/main/java/no/nav/k9/konstant/Konstant.java, pom.xml
Inneholder pr. nå forventet saksbehandlingstid.
=> Legger til ny modul for konstanter.

innsyn/pom.xml
Release notes: https://github.com/navikt/k9-sak/releases/tag/4.1.8
=> Bumper k9-kontrakt.

ettersendelse/src/main/java/no/nav/k9/ettersendelse/Ettersendelse.java, ettersendelse/src/main/java/no/nav/k9/ettersendelse/EttersendelseType.java, ettersendelse/src/main/java/no/nav/k9/ettersendelse/EttersendelseValidator.java, ettersendelse/src/main/java/no/nav/k9/ettersendelse/Pleietrengende.java, ettersendelse/src/test/java/no/nav/k9/ettersendelse/TestUtils.java, ettersendelse/src/test/resources/ettersendelse.json
For digital ettersendelse til k9-sak.
Bør være bakoverkompatibelt :crossed_fingers:
=> Utvider Ettersendelse med pleietrengende og type

innsyn/src/main/java/no/nav/k9/innsyn/sak/Behandling.java, innsyn/src/main/java/no/nav/k9/innsyn/sak/InnsendingInfo.java, innsyn/src/main/java/no/nav/k9/innsyn/sak/InnsendingStatus.java, innsyn/src/main/java/no/nav/k9/innsyn/sak/InnsendingType.java, innsyn/src/test/java/no/nav/k9/innsyn/sak/BehandlingTest.java
- Renamer SøknadInfo til InnsendingInfo.
- Legger til InnsendingType for å indikere søknad eller ettersendelse.
- Renamer feltet søknader til innsendinger, med støtte for gammelt navn.
=> Refaktorerer SøknadInfo.

soknad/src/main/java/no/nav/k9/søknad/felles/personopplysninger/Utenlandsopphold.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/PleiepengerSyktBarn.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/pls/v1/YtelseEksempel.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/psb/YtelseEksempel.java, soknad/src/test/resources/ytelse/psb/komplett-søknad.json, soknad/src/test/resources/ytelse/psb/søknad-med-endring.json, soknad/src/test/resources/ytelse/psb/søknad-null-feil.json
Feltet legges til både i Utenlandsopphold og på PleiepengerSyktBarn nivå.
=> Legger til info om søker er sammen med barnet.

soknad/src/main/java/no/nav/k9/søknad/TidUtils.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/ung/v1/UngSøknadstype.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/ung/v1/Ungdomsytelse.java, soknad/src/main/java/no/nav/k9/søknad/ytelse/ung/v1/UngdomsytelseSøknadValidator.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/ung/YtelseEksempel.java, soknad/src/test/java/no/nav/k9/søknad/ytelse/ung/v1/ValideringTest.java
Krever at tilOgMed dato er satt på søknadsperiode om søknadstype er RAPPORTERING_SØKNAD. Ellers kan tilOgMed dato være satt til tidenes ende (9999-12-31).
=> Definerer søknadstype og validerer tom. dato på søknadsperiode.

soknad/src/main/java/no/nav/k9/søknad/ytelse/omsorgspenger/utvidetrett/v1/OmsorgspengerKroniskSyktBarn.java
Dette slik at disse feltene kan tas med fra brukerdialog og vises i k9-sak
=> TSFF-970: Legg til boolean og beskrivelse for høyere risiko i kronisk syk

soknad/src/main/java/no/nav/k9/søknad/ytelse/olp/v1/Opplæringspenger.java
=> Revert "Bruker kursperioder som søknadsperioder for opplæringspenger"

konstant/src/main/java/no/nav/k9/konstant/Konstant.java
Saksbehandlerne har fått ned forventet saksbehandlingstid til 8 uker.
Endrer til 8 uker
=> Endrer saksbehandlingstid til 8 uker
